# Generated by Django 3.2.7 on 2021-09-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20210916_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmodel',
            name='code',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
