# Generated by Django 3.2.7 on 2021-09-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auto_20210917_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmodel',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
