# Generated by Django 3.2.7 on 2021-09-20 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_pricingmodel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='last_session',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_billed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pricingmodel',
            name='code',
            field=models.CharField(choices=[('WhatsApp Only', 'WABA_ONLY'), ('SMS Only', 'SMS_ONLY'), ('WhatsApp and SMS', 'WHATSAPP_SMS')], default=None, max_length=20, unique=True),
        ),
    ]
