# Generated by Django 3.2.7 on 2021-09-21 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20210920_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
