# Generated by Django 3.2.7 on 2021-09-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_assignment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='pricing_model',
        ),
    ]
