# Generated by Django 3.2.7 on 2021-09-23 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0015_subscription_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='last_billed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='guardian',
            name='session_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('user', 'branch')},
        ),
        migrations.CreateModel(
            name='AssignmentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.assignment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.subscription')),
            ],
            options={
                'unique_together': {('assignment', 'subscription')},
            },
        ),
    ]
