# Generated by Django 3.2.7 on 2021-09-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='package',
            field=models.CharField(choices=[('termly', 'Per Term'), ('monthly', 'Per Month'), ('custom', 'Custom Payment')], default='custom', max_length=10),
        ),
    ]
