# Generated by Django 3.2.7 on 2021-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscriptiontransaction_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontransaction',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='subscriptiontransaction',
            name='merchant_request_id',
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='payment_id',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
