# Generated by Django 3.2.7 on 2021-09-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210922_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='paybill_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
